steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mixpanel-tableau-pipeline:$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/mixpanel-tableau-pipeline:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mixpanel-tableau-pipeline:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mixpanel-tableau-pipeline:latest']

images:
  - 'gcr.io/$PROJECT_ID/mixpanel-tableau-pipeline:latest'

options:
  logging: CLOUD_LOGGING_ONLY
